-- ============================================================================
-- VIBER'S TOOLKIT — Complete Database Schema
-- ============================================================================
-- Platform: Supabase (PostgreSQL 15+)
-- App: Viber's Toolkit — personal productivity suite
-- Author: Bhaskar Mantrala
-- Last updated: 2026-04-06
--
-- HOW TO USE:
-- 1. Create a new Supabase project at https://supabase.com
-- 2. Go to SQL Editor → New Query
-- 3. Copy-paste this ENTIRE file and click Run
-- 4. After running, sign up on the app, then manually set your admin flag:
--    UPDATE profiles SET is_admin = true WHERE email = 'your-email@example.com';
--
-- NOTES:
-- - This file is idempotent — safe to run multiple times (uses IF NOT EXISTS)
-- - All tables use Row Level Security (RLS) for data isolation
-- - Each user can only see/modify their own data unless they're an admin
-- - The is_admin() function uses SECURITY DEFINER to bypass RLS safely
-- ============================================================================


-- ============================================================================
-- FUNCTION: is_admin()
-- ============================================================================
-- WHY: RLS policies need to check if the current user is an admin.
--      But if we query the profiles table inside an RLS policy on profiles,
--      it creates infinite recursion. SECURITY DEFINER bypasses RLS,
--      breaking the recursion while still being secure.
-- USED BY: All "Admin can..." RLS policies across tables.
-- ============================================================================
CREATE OR REPLACE FUNCTION is_admin()
RETURNS BOOLEAN AS $$
  SELECT EXISTS (
    SELECT 1 FROM profiles WHERE id = auth.uid() AND (is_admin = true OR access @> '{admin}')
  );
$$ LANGUAGE sql SECURITY DEFINER;


-- ============================================================================
-- TABLE: vibes
-- ============================================================================
-- WHY: Core data table. Stores all tasks/ideas (called "vibes").
-- COLUMNS:
--   id            — UUID auto-generated by Supabase. Never sent from client.
--   user_id       — Links to auth.users. RLS ensures user isolation.
--   text          — The vibe content. Required.
--   status        — Workflow state: spark → in_progress → scheduled → done
--                   "spark" = new idea, "scheduled" = has a due date
--   category      — Optional grouping: Work, Personal, Creative, Learning, Health
--   time_spent    — Minutes tracked via the timer feature (integer, not float)
--   notes         — Free text for URLs, justifications, context. Supports links.
--   due_date      — When the vibe is due. Null = no deadline. Color-coded in UI:
--                   red = overdue, orange = within 3 days, green = future
--   position      — Sort order within a kanban column (for future drag reorder)
--   completed_at  — Auto-set when status changes to "done". Shows completion date.
--   deleted_at    — Soft delete. Null = active. Set = in "Recently Deleted" trash.
--                   WHY soft delete: allows restore, syncs across devices.
--   created_at    — When the vibe was first created.
--   updated_at    — Auto-updated by trigger on every change.
-- ============================================================================
CREATE TABLE IF NOT EXISTS vibes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  text TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'spark',
  category TEXT,
  time_spent INTEGER DEFAULT 0,
  notes TEXT DEFAULT '',
  due_date DATE,
  position INTEGER DEFAULT 0,
  completed_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- WHY: Speeds up queries filtering by user_id (every query uses this)
CREATE INDEX IF NOT EXISTS idx_vibes_user_id ON vibes(user_id);

-- WHY: Each user should only see their own vibes. Without RLS, any
-- authenticated user could read all vibes in the table using the anon key.
ALTER TABLE vibes ENABLE ROW LEVEL SECURITY;

-- User policies — standard CRUD isolation by user_id
CREATE POLICY "Users can read own vibes"
  ON vibes FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own vibes"
  ON vibes FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own vibes"
  ON vibes FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own vibes"
  ON vibes FOR DELETE USING (auth.uid() = user_id);

-- Admin policies — admin dashboard needs to see all vibes for stats
CREATE POLICY "Admin can read all vibes"
  ON vibes FOR SELECT USING (is_admin());

-- WHY: Super admin can delete a user's vibes when disabling/removing them
CREATE POLICY "Admin can delete all vibes"
  ON vibes FOR DELETE USING (is_admin());

-- WHY: updated_at should reflect the last modification time automatically.
-- The app doesn't send updated_at — the DB handles it via this trigger.
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS vibes_updated_at ON vibes;
CREATE TRIGGER vibes_updated_at
  BEFORE UPDATE ON vibes
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();


-- ============================================================================
-- TABLE: profiles
-- ============================================================================
-- WHY: Supabase's auth.users table is NOT queryable with the anon key.
--      We need a public-facing table to store user info (name, email, role).
--      This table is auto-populated by a trigger when a user signs up.
-- COLUMNS:
--   id         — Same UUID as auth.users.id (1:1 relationship)
--   email      — Copied from auth for display in admin dashboard
--   full_name  — From signup form, stored in user_metadata
--   is_admin   — Admin flag. Only admins can see all users/vibes.
--   disabled   — Soft-disable. Disabled users can't log in but aren't deleted.
--               WHY not delete: deleting profiles doesn't delete auth.users
--               (needs service role key). Disabling is safer and reversible.
--   created_at — When the user signed up
-- ============================================================================
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT,
  full_name TEXT,
  is_admin BOOLEAN DEFAULT false,
  disabled BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- WHY: Users need to read their own profile (for greeting, settings)
CREATE POLICY "Users can read own profile"
  ON profiles FOR SELECT USING (auth.uid() = id);

-- WHY: Admin dashboard shows all users with names, emails, roles
CREATE POLICY "Admin can read all profiles"
  ON profiles FOR SELECT USING (is_admin());

-- WHY: Super admin can toggle is_admin and disabled flags
CREATE POLICY "Admin can update all profiles"
  ON profiles FOR UPDATE USING (is_admin());

-- WHY: Super admin can remove profiles (though we prefer disable over delete)
CREATE POLICY "Admin can delete profiles"
  ON profiles FOR DELETE USING (is_admin());

-- WHY: The handle_new_user() trigger inserts a profile on signup.
--      The trigger runs as SECURITY DEFINER (bypasses RLS), but Supabase
--      still checks INSERT policies. This allows the insert to succeed.
CREATE POLICY "Allow insert via trigger"
  ON profiles FOR INSERT WITH CHECK (true);


-- ============================================================================
-- TABLE: app_settings
-- ============================================================================
-- WHY: Dynamic configuration without redeploying. Currently stores max_users
--      limit. Super admin can change it from the dashboard UI.
--      Previously this was an env var (NEXT_PUBLIC_MAX_USERS) but the user
--      wanted to change it without touching Cloudflare config.
-- ============================================================================
CREATE TABLE IF NOT EXISTS app_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;

-- WHY: Signup flow needs to read max_users BEFORE the user is authenticated.
--      This is just configuration data (not sensitive), so public read is safe.
CREATE POLICY "Anyone can read settings"
  ON app_settings FOR SELECT USING (true);

-- WHY: Only admins should change app configuration
CREATE POLICY "Admin can update settings"
  ON app_settings FOR UPDATE USING (is_admin());

CREATE POLICY "Admin can insert settings"
  ON app_settings FOR INSERT WITH CHECK (is_admin());

-- Default: 15 max users (changeable from admin dashboard)
INSERT INTO app_settings (key, value)
VALUES ('max_users', '15')
ON CONFLICT (key) DO NOTHING;


-- ============================================================================
-- TABLE: id_documents
-- ============================================================================
-- WHY: Tracks identity documents (US + India) for the user and their family.
--      No sensitive data stored — only type, label, expiry date, renewal URL.
--      Used by the ID Tracker tool for expiry reminders.
-- COLUMNS:
--   id_type      — e.g. 'us_passport', 'oci_card' (matches constants in code)
--   country      — 'US' or 'IN'
--   label        — user-facing name, e.g. "My US Passport"
--   owner_name   — family member name, e.g. "Bhaskar", "Mounika", "Dad"
--   description  — optional notes
--   expiry_date  — null for non-expiring IDs (SSN, PAN, Aadhaar, Voter ID)
--   renewal_url  — pre-filled from constants, user can override
--   reminder_days — Postgres integer array, e.g. {90,30,7} = remind at 90, 30, 7 days before
-- ============================================================================
CREATE TABLE IF NOT EXISTS id_documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  id_type TEXT NOT NULL,
  country TEXT NOT NULL DEFAULT 'US',
  label TEXT NOT NULL,
  owner_name TEXT NOT NULL DEFAULT '',
  description TEXT DEFAULT '',
  expiry_date DATE,
  renewal_url TEXT DEFAULT '',
  reminder_days INTEGER[] DEFAULT '{90,30,7}',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_id_documents_user_id ON id_documents(user_id);
-- WHY: Fast lookups for daily expiry reminder checks
CREATE INDEX IF NOT EXISTS idx_id_documents_expiry ON id_documents(expiry_date)
  WHERE expiry_date IS NOT NULL;

ALTER TABLE id_documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own id_documents"
  ON id_documents FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own id_documents"
  ON id_documents FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own id_documents"
  ON id_documents FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own id_documents"
  ON id_documents FOR DELETE USING (auth.uid() = user_id);
-- WHY: Admin dashboard may show all users' expiring IDs in future
CREATE POLICY "Admin can read all id_documents"
  ON id_documents FOR SELECT USING (is_admin());

-- Reuse existing update_updated_at() trigger function
DROP TRIGGER IF EXISTS id_documents_updated_at ON id_documents;
CREATE TRIGGER id_documents_updated_at
  BEFORE UPDATE ON id_documents
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();


-- ============================================================================
-- FUNCTION: get_user_count()
-- ============================================================================
-- WHY: Signup needs to check how many users exist BEFORE the new user is
--      authenticated. Normal RLS would block the query. This function uses
--      SECURITY DEFINER to bypass RLS and returns just a number (no user data).
--      Called via: supabase.rpc('get_user_count')
-- ============================================================================
CREATE OR REPLACE FUNCTION public.get_user_count()
RETURNS INT AS $$
  SELECT COUNT(*)::INT FROM public.profiles;
$$ LANGUAGE sql SECURITY DEFINER SET search_path = public;


-- ============================================================================
-- FUNCTION + TRIGGER: handle_new_user()
-- ============================================================================
-- WHY: When a user signs up via Supabase Auth, we need to auto-create their
--      profile row. This trigger fires AFTER INSERT on auth.users.
--
-- IMPORTANT DETAILS:
-- - SECURITY DEFINER: runs with the function owner's permissions (bypasses RLS)
-- - SET search_path = public: required so the function finds the profiles table
--   (without this, it fails silently with "Database error saving new user")
-- - GRANT TO supabase_auth_admin: the auth system needs permission to call it
--   (without this, signup fails with permission denied)
-- - ON CONFLICT DO NOTHING: prevents errors if profile already exists
-- - raw_user_meta_data: Supabase stores the signup { data: { full_name } } here
-- ============================================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name)
  VALUES (
    NEW.id,
    NEW.email,
    NEW.raw_user_meta_data->>'full_name'
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Grant execute to Supabase auth system
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO supabase_auth_admin;

-- Trigger on auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();


-- ============================================================================
-- TABLE: cricket_teams (Multi-Team Support)
-- ============================================================================
-- WHY: Enables multi-team support. Each cricket team is a separate tenant.
--      All cricket tables reference a team via team_id FK.
-- COLUMNS:
--   id            — UUID auto-generated
--   name          — Team display name (unique)
--   slug          — URL-safe identifier, e.g. 'sunrisers-manteca' (unique)
--   logo_url      — Team logo (optional)
--   primary_color — Hex color for branding (default: '#0369a1')
--   owner_id      — FK to auth.users, the team creator/owner (ON DELETE RESTRICT)
--   deleted_at    — Soft delete timestamp
--   created_at    — When the team was created
--   updated_at    — Auto-updated by trigger
-- RLS: Any authenticated user can read non-deleted teams. Owner can update.
-- ============================================================================
CREATE TABLE IF NOT EXISTS cricket_teams (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name          TEXT NOT NULL,
  slug          TEXT NOT NULL,
  logo_url      TEXT,
  primary_color TEXT DEFAULT '#0369a1',
  owner_id      UUID NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  deleted_at    TIMESTAMPTZ,
  created_at    TIMESTAMPTZ DEFAULT now(),
  updated_at    TIMESTAMPTZ DEFAULT now(),

  CONSTRAINT cricket_teams_slug_unique UNIQUE (slug),
  CONSTRAINT cricket_teams_name_unique UNIQUE (name),
  CONSTRAINT cricket_teams_slug_format CHECK (slug ~ '^[a-z0-9]([a-z0-9-]*[a-z0-9])?$')
);


-- ============================================================================
-- TABLE: team_members
-- ============================================================================
-- WHY: Junction table linking users to teams with a role.
--      Used by RLS helper functions to scope all cricket data by team.
-- COLUMNS:
--   id        — UUID auto-generated
--   team_id   — FK to cricket_teams (ON DELETE RESTRICT)
--   user_id   — FK to auth.users (ON DELETE CASCADE)
--   role      — 'owner' | 'admin' | 'player' (owner role protected by trigger)
--   joined_at — When the user joined the team
-- RLS: Members can see their team's roster. Team admin can add/update/remove.
-- ============================================================================
CREATE TABLE IF NOT EXISTS team_members (
  id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  team_id   UUID NOT NULL REFERENCES cricket_teams(id) ON DELETE RESTRICT,
  user_id   UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role      TEXT NOT NULL DEFAULT 'player' CHECK (role IN ('owner', 'admin', 'player')),
  joined_at TIMESTAMPTZ DEFAULT now(),

  CONSTRAINT team_members_unique UNIQUE (team_id, user_id)
);


-- ============================================================================
-- TABLE: team_invites (Phase 5: Team Onboarding)
-- ============================================================================
-- WHY: Invite link infrastructure for team onboarding. Team admins generate
--      invite tokens (URLs) that new users can use to join a specific team.
--      Tokens have optional expiry and max-use limits.
-- COLUMNS:
--   id         — UUID auto-generated
--   team_id    — FK to cricket_teams (CASCADE on delete)
--   token      — UUID unique invite token (used in invite URL)
--   created_by — FK to auth.users who created the invite
--   expires_at — Default 30 days from creation
--   max_uses   — NULL = unlimited uses
--   use_count  — Incremented on each accept
--   is_active  — Can be deactivated by admin
-- RLS: Team admin or global admin can read/create/update.
-- RPCs:
--   validate_invite_token(token) — public, no auth, returns team info or NULL
--   accept_invite(token)         — authenticated, adds user to team + cricket access
--   create_team(name, slug, color) — global admin only, creates team + owner membership
--   suggest_players(query, team_id) — autocomplete for adding players from
--     team members (not yet on roster) and other-team players (LATERAL JOIN enrichment)
-- TRIGGER: sync_player_profile_across_teams — on UPDATE of cricket_players,
--   syncs global fields (name, email, photo_url, phone, player_role, batting/bowling
--   style, shirt_size, cricclub_id) to all other records with same user_id.
--   Team-specific fields (jersey_number, designation, is_guest, is_active, team_id)
--   are NOT synced. Uses pg_trigger_depth() guard to prevent recursion.
-- ============================================================================
CREATE TABLE IF NOT EXISTS team_invites (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  team_id     UUID NOT NULL REFERENCES cricket_teams(id) ON DELETE CASCADE,
  token       UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  created_by  UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  expires_at  TIMESTAMPTZ NOT NULL DEFAULT (now() + interval '30 days'),
  max_uses    INTEGER DEFAULT NULL,
  use_count   INTEGER NOT NULL DEFAULT 0,
  is_active   BOOLEAN NOT NULL DEFAULT true,
  created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_team_invites_token ON team_invites(token);
CREATE INDEX idx_team_invites_team ON team_invites(team_id);


-- ============================================================================
-- MULTI-TEAM: team_id Foreign Key on All Cricket Tables
-- ============================================================================
-- WHY: Every cricket table has a `team_id UUID NOT NULL REFERENCES cricket_teams(id)`
--      column added by the multi-team migration. This scopes all data by team.
--
-- Parent tables (9): cricket_players, cricket_seasons, cricket_expenses,
--   cricket_settlements, cricket_season_fees, cricket_sponsorships,
--   cricket_gallery, cricket_schedule_matches, practice_matches
--
-- Child tables (5, auto-populated via trigger from parent):
--   practice_balls, practice_innings, practice_match_players,
--   cricket_gallery_comments, cricket_notifications
--
-- Tables WITHOUT team_id (use parent join for RLS):
--   cricket_expense_splits, cricket_gallery_tags, cricket_gallery_likes,
--   cricket_comment_reactions
-- ============================================================================


-- ============================================================================
-- HELPER FUNCTIONS: Multi-Team RLS
-- ============================================================================
-- WHY: RLS policies use these SECURITY DEFINER functions for team-scoped access.
--      All are STABLE (cacheable per statement) for performance.
--
-- user_team_ids()          — Returns all team IDs the current user belongs to
-- is_team_admin(team_id)   — TRUE if current user is owner/admin of the team
-- is_team_member(team_id)  — TRUE if current user is any member of the team
-- is_global_admin()        — TRUE if current user has 'admin' in profiles.access
-- is_active_scorer(match_id) — TRUE if current user is active scorer or creator
-- ============================================================================


-- ============================================================================
-- POST-SETUP: Run these manually after signing up
-- ============================================================================

-- 1. Backfill existing users (if you had users before adding profiles table)
-- INSERT INTO profiles (id, email, full_name)
-- SELECT id, email, raw_user_meta_data->>'full_name'
-- FROM auth.users
-- ON CONFLICT (id) DO NOTHING;

-- 2. Set yourself as admin (replace with your email)
-- UPDATE profiles SET is_admin = true WHERE email = 'your-email@example.com';

-- 3. Update user metadata (if name was missing at signup)
-- This runs via the app: supabase.auth.updateUser({ data: { full_name: 'Name' } })
