-- ============================================================================
-- VIBER'S TOOLKIT — Complete Database Schema
-- ============================================================================
-- Platform: Supabase (PostgreSQL 15+)
-- App: Viber's Toolkit — personal productivity suite
-- Author: Bhaskar Mantrala
-- Last updated: 2026-03-13
--
-- HOW TO USE:
-- 1. Create a new Supabase project at https://supabase.com
-- 2. Go to SQL Editor → New Query
-- 3. Copy-paste this ENTIRE file and click Run
-- 4. After running, sign up on the app, then manually set your admin flag:
--    UPDATE profiles SET is_admin = true WHERE email = 'your-email@example.com';
--
-- NOTES:
-- - This file is idempotent — safe to run multiple times (uses IF NOT EXISTS)
-- - All tables use Row Level Security (RLS) for data isolation
-- - Each user can only see/modify their own data unless they're an admin
-- - The is_admin() function uses SECURITY DEFINER to bypass RLS safely
-- ============================================================================


-- ============================================================================
-- FUNCTION: is_admin()
-- ============================================================================
-- WHY: RLS policies need to check if the current user is an admin.
--      But if we query the profiles table inside an RLS policy on profiles,
--      it creates infinite recursion. SECURITY DEFINER bypasses RLS,
--      breaking the recursion while still being secure.
-- USED BY: All "Admin can..." RLS policies across tables.
-- ============================================================================
CREATE OR REPLACE FUNCTION is_admin()
RETURNS BOOLEAN AS $$
  SELECT EXISTS (
    SELECT 1 FROM profiles WHERE id = auth.uid() AND is_admin = true
  );
$$ LANGUAGE sql SECURITY DEFINER;


-- ============================================================================
-- TABLE: vibes
-- ============================================================================
-- WHY: Core data table. Stores all tasks/ideas (called "vibes").
-- COLUMNS:
--   id            — UUID auto-generated by Supabase. Never sent from client.
--   user_id       — Links to auth.users. RLS ensures user isolation.
--   text          — The vibe content. Required.
--   status        — Workflow state: spark → in_progress → scheduled → done
--                   "spark" = new idea, "scheduled" = has a due date
--   category      — Optional grouping: Work, Personal, Creative, Learning, Health
--   time_spent    — Minutes tracked via the timer feature (integer, not float)
--   notes         — Free text for URLs, justifications, context. Supports links.
--   due_date      — When the vibe is due. Null = no deadline. Color-coded in UI:
--                   red = overdue, orange = within 3 days, green = future
--   position      — Sort order within a kanban column (for future drag reorder)
--   completed_at  — Auto-set when status changes to "done". Shows completion date.
--   deleted_at    — Soft delete. Null = active. Set = in "Recently Deleted" trash.
--                   WHY soft delete: allows restore, syncs across devices.
--   created_at    — When the vibe was first created.
--   updated_at    — Auto-updated by trigger on every change.
-- ============================================================================
CREATE TABLE IF NOT EXISTS vibes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  text TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'spark',
  category TEXT,
  time_spent INTEGER DEFAULT 0,
  notes TEXT DEFAULT '',
  due_date DATE,
  position INTEGER DEFAULT 0,
  completed_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- WHY: Speeds up queries filtering by user_id (every query uses this)
CREATE INDEX IF NOT EXISTS idx_vibes_user_id ON vibes(user_id);

-- WHY: Each user should only see their own vibes. Without RLS, any
-- authenticated user could read all vibes in the table using the anon key.
ALTER TABLE vibes ENABLE ROW LEVEL SECURITY;

-- User policies — standard CRUD isolation by user_id
CREATE POLICY "Users can read own vibes"
  ON vibes FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own vibes"
  ON vibes FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own vibes"
  ON vibes FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own vibes"
  ON vibes FOR DELETE USING (auth.uid() = user_id);

-- Admin policies — admin dashboard needs to see all vibes for stats
CREATE POLICY "Admin can read all vibes"
  ON vibes FOR SELECT USING (is_admin());

-- WHY: Super admin can delete a user's vibes when disabling/removing them
CREATE POLICY "Admin can delete all vibes"
  ON vibes FOR DELETE USING (is_admin());

-- WHY: updated_at should reflect the last modification time automatically.
-- The app doesn't send updated_at — the DB handles it via this trigger.
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS vibes_updated_at ON vibes;
CREATE TRIGGER vibes_updated_at
  BEFORE UPDATE ON vibes
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();


-- ============================================================================
-- TABLE: profiles
-- ============================================================================
-- WHY: Supabase's auth.users table is NOT queryable with the anon key.
--      We need a public-facing table to store user info (name, email, role).
--      This table is auto-populated by a trigger when a user signs up.
-- COLUMNS:
--   id         — Same UUID as auth.users.id (1:1 relationship)
--   email      — Copied from auth for display in admin dashboard
--   full_name  — From signup form, stored in user_metadata
--   is_admin   — Admin flag. Only admins can see all users/vibes.
--   disabled   — Soft-disable. Disabled users can't log in but aren't deleted.
--               WHY not delete: deleting profiles doesn't delete auth.users
--               (needs service role key). Disabling is safer and reversible.
--   created_at — When the user signed up
-- ============================================================================
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT,
  full_name TEXT,
  is_admin BOOLEAN DEFAULT false,
  disabled BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- WHY: Users need to read their own profile (for greeting, settings)
CREATE POLICY "Users can read own profile"
  ON profiles FOR SELECT USING (auth.uid() = id);

-- WHY: Admin dashboard shows all users with names, emails, roles
CREATE POLICY "Admin can read all profiles"
  ON profiles FOR SELECT USING (is_admin());

-- WHY: Super admin can toggle is_admin and disabled flags
CREATE POLICY "Admin can update all profiles"
  ON profiles FOR UPDATE USING (is_admin());

-- WHY: Super admin can remove profiles (though we prefer disable over delete)
CREATE POLICY "Admin can delete profiles"
  ON profiles FOR DELETE USING (is_admin());

-- WHY: The handle_new_user() trigger inserts a profile on signup.
--      The trigger runs as SECURITY DEFINER (bypasses RLS), but Supabase
--      still checks INSERT policies. This allows the insert to succeed.
CREATE POLICY "Allow insert via trigger"
  ON profiles FOR INSERT WITH CHECK (true);


-- ============================================================================
-- TABLE: app_settings
-- ============================================================================
-- WHY: Dynamic configuration without redeploying. Currently stores max_users
--      limit. Super admin can change it from the dashboard UI.
--      Previously this was an env var (NEXT_PUBLIC_MAX_USERS) but the user
--      wanted to change it without touching Cloudflare config.
-- ============================================================================
CREATE TABLE IF NOT EXISTS app_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;

-- WHY: Signup flow needs to read max_users BEFORE the user is authenticated.
--      This is just configuration data (not sensitive), so public read is safe.
CREATE POLICY "Anyone can read settings"
  ON app_settings FOR SELECT USING (true);

-- WHY: Only admins should change app configuration
CREATE POLICY "Admin can update settings"
  ON app_settings FOR UPDATE USING (is_admin());

CREATE POLICY "Admin can insert settings"
  ON app_settings FOR INSERT WITH CHECK (is_admin());

-- Default: 15 max users (changeable from admin dashboard)
INSERT INTO app_settings (key, value)
VALUES ('max_users', '15')
ON CONFLICT (key) DO NOTHING;


-- ============================================================================
-- FUNCTION: get_user_count()
-- ============================================================================
-- WHY: Signup needs to check how many users exist BEFORE the new user is
--      authenticated. Normal RLS would block the query. This function uses
--      SECURITY DEFINER to bypass RLS and returns just a number (no user data).
--      Called via: supabase.rpc('get_user_count')
-- ============================================================================
CREATE OR REPLACE FUNCTION public.get_user_count()
RETURNS INT AS $$
  SELECT COUNT(*)::INT FROM public.profiles;
$$ LANGUAGE sql SECURITY DEFINER SET search_path = public;


-- ============================================================================
-- FUNCTION + TRIGGER: handle_new_user()
-- ============================================================================
-- WHY: When a user signs up via Supabase Auth, we need to auto-create their
--      profile row. This trigger fires AFTER INSERT on auth.users.
--
-- IMPORTANT DETAILS:
-- - SECURITY DEFINER: runs with the function owner's permissions (bypasses RLS)
-- - SET search_path = public: required so the function finds the profiles table
--   (without this, it fails silently with "Database error saving new user")
-- - GRANT TO supabase_auth_admin: the auth system needs permission to call it
--   (without this, signup fails with permission denied)
-- - ON CONFLICT DO NOTHING: prevents errors if profile already exists
-- - raw_user_meta_data: Supabase stores the signup { data: { full_name } } here
-- ============================================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name)
  VALUES (
    NEW.id,
    NEW.email,
    NEW.raw_user_meta_data->>'full_name'
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Grant execute to Supabase auth system
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO supabase_auth_admin;

-- Trigger on auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();


-- ============================================================================
-- POST-SETUP: Run these manually after signing up
-- ============================================================================

-- 1. Backfill existing users (if you had users before adding profiles table)
-- INSERT INTO profiles (id, email, full_name)
-- SELECT id, email, raw_user_meta_data->>'full_name'
-- FROM auth.users
-- ON CONFLICT (id) DO NOTHING;

-- 2. Set yourself as admin (replace with your email)
-- UPDATE profiles SET is_admin = true WHERE email = 'your-email@example.com';

-- 3. Update user metadata (if name was missing at signup)
-- This runs via the app: supabase.auth.updateUser({ data: { full_name: 'Name' } })
